services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    Symfony\Bundle\FrameworkBundle\KernelBrowser: '@test.client'
